name: Workflow Spotify

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Instalar Dependências do Node
      run: npm install

    - name: Executar e Testar Banco de Dados
      run: |
        bash scripts/setup_db.sh
        echo "Banco de dados e scripts DDL/DML validados com sucesso!"